on:  workflow_dispatch

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19


      - name: Publish tekton images and generate release manifests
        run: |
          sudo apt-get update -y && sudo apt-get install -y qemu-user-static
          echo ${{ secrets.QUAY_PASSWORD }} | podman login -u="${{ secrets.QUAY_BOT }}" --password-stdin quay.io
          export RELEASE_VERSION="v0.0.1"
          make release

  

