on:  workflow_dispatch

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19


      - name: Publish tekton images and generate release manifests
        run: |
          echo ${{ secrets.QUAY_PASSWORD }} | podman login -u="${{ secrets.QUAY_BOT }}" --password-stdin quay.io
          export RELEASE_VERSION="v0.0.1"
          make release

  
      - name: Publish ARM tekton images and generate release manifests
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: fedora_latest
          run: |
            echo ${{ secrets.QUAY_PASSWORD }} | podman login -u="${{ secrets.QUAY_BOT }}" --password-stdin quay.io
            export RELEASE_VERSION="v0.0.1"
            make release
